BaseURL = "http://blog.negimic.com/"
languageCode = "ja-jp"
title = "negimic blog"
theme = "casper"
copyright = "2016 negimic All Rights Reserved"
# disqusShortname = "negimic"

[params]
author = "negimic"
description = "ねぎみくのブログ |ω・)"
bio = "渋谷で働くフロントエンドエンジニア。４年目突入。"
googleAnalyticsUserID = "UA-60588073-1"

# [permalinks]
#   post = "/:slug/"
